name: Jass Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install
      working-directory: ./jaspreetassign

    - name: Run Tests
      run: npm test
      working-directory: ./jaspreetassign

    - name: Build Project
      run: npm run build
      working-directory: ./jaspreetassign
